### ISSUE TITLE
sys/types in aes_tables.c

### ISSUE THREAD

**Issue by asdfjkl** [unfrozen/stm8_libs#3]
Dear Richard,

thanks very much for your awesome collection of STM8 implementations!

I am trying to use your AES implementation for the STM8 but was unable to compile the AES lib. I am using sdcc (4.1.0) on Linux. Compiling I get the error message for the file aes_tables.c, where the include "sys/types.h" fails (no such file or directory). I am not sure if this is referring to the standard gcc types.h (which seems odd) or some STM8 specific header file. I am also not sure what kind of header definitions are actually used in aes_tables.c. As far as I can see, BYTE is just a custom typedef of char...

Any clue what might be the issue?

**Comment by unfrozen** [comment]
I think the "sys/types.h" is a relic from my FreeBSD code. I took it out and it compiles.
Yes, BYTE is just an unsigned char. Another relic, I believe.
It should build for you now.

PLEASE NOTE: SDCC 4.2 uses a new calling method that affects inline assembly. I have updated many libraries, but not (yet) AES.

**Comment by unfrozen** [comment]
On 10/11/22 12:46 AM, Dominik Klein wrote:

> thanks very much for your awesome collection of STM8 implementations!

Hi Dominik, I'm glad to share.

> Compiling I
> get the error message for the file aes_tables.c, where the include
> "sys/types.h" fails (no such file or directory).

This is not needed, and I think it is a relic from some old code. I took
it out.

I also updated Makefile to build aes_tables.h if needed. It is generated
by aes_tables.c

You may have a notification from github, but this email is in case you
didn't.

All the best,
-Richard

**Comment by asdfjkl** [comment]
thanks very much for your support. ~~I am sure I'll get it running now!~~ It's compiling and working fine now!
